using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using NexaOps.Application.Auth.DTOs;
using NexaOps.Application.Companies.DTOs;
using NexaOps.IntegrationTests.Common;

namespace NexaOps.IntegrationTests;

public class CompaniesApiTests : IClassFixture<CustomWebApplicationFactory>
{
    private readonly HttpClient _client;

    public CompaniesApiTests(CustomWebApplicationFactory factory)
    {
        _client = factory.CreateClient();
    }

    private async Task<string> RegisterAndGetTokenAsync(string? prefix = null)
    {
        var tag = prefix ?? Guid.NewGuid().ToString();
        var registerRequest = new RegisterRequest
        {
            Name = $"Owner {tag}",
            Email = $"owner.{tag}@nexaops.com",
            Password = "password123"
        };
        var response = await _client.PostAsJsonAsync("/auth/register", registerRequest);
        var authResult = await response.Content.ReadFromJsonAsync<AuthResponse>();
        return authResult!.AccessToken;
    }

    [Fact]
    public async Task CreateCompany_WithoutToken_Returns401Unauthorized()
    {
        // Arrange
        var request = new CreateCompanyRequest
        {
            Name = "No Auth Company"
        };

        // Act
        var response = await _client.PostAsJsonAsync("/companies", request);

        // Assert
        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
    }

    [Fact]
    public async Task CreateCompany_ValidPayload_Returns201CreatedAndAutoGeneratedSlug()
    {
        // Arrange
        var token = await RegisterAndGetTokenAsync();
        var request = new CreateCompanyRequest
        {
            Name = "Công Ty Công Nghệ NexaOps",
            Description = "Doanh nghiệp công nghệ"
        };

        var message = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request)
        };
        message.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

        // Act
        var response = await _client.SendAsync(message);

        // Assert
        Assert.Equal(HttpStatusCode.Created, response.StatusCode);
        var company = await response.Content.ReadFromJsonAsync<CompanyResponse>();
        Assert.NotNull(company);
        Assert.Equal(request.Name, company.Name);
        Assert.StartsWith("cong-ty-cong-nghe-nexaops-", company.Slug);
        Assert.True(company.IsActive);
    }

    [Fact]
    public async Task CreateCompany_DuplicateSlug_Returns400BadRequest()
    {
        // Arrange
        var token = await RegisterAndGetTokenAsync();
        var fixedSlug = $"fixed-slug-{Guid.NewGuid():N}";

        var request1 = new CreateCompanyRequest
        {
            Name = "Company One",
            Slug = fixedSlug
        };
        var msg1 = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request1)
        };
        msg1.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var res1 = await _client.SendAsync(msg1);
        Assert.Equal(HttpStatusCode.Created, res1.StatusCode);

        // Act - Try creating another company with identical custom slug
        var request2 = new CreateCompanyRequest
        {
            Name = "Company Two",
            Slug = fixedSlug
        };
        var msg2 = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request2)
        };
        msg2.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var res2 = await _client.SendAsync(msg2);

        // Assert
        Assert.Equal(HttpStatusCode.BadRequest, res2.StatusCode);
    }

    [Fact]
    public async Task FindMyCompanies_ReturnsUserCompanies()
    {
        // Arrange
        var token = await RegisterAndGetTokenAsync();

        var request = new CreateCompanyRequest { Name = "My Unique Company" };
        var msgCreate = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request)
        };
        msgCreate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        await _client.SendAsync(msgCreate);

        // Act
        var msgGet = new HttpRequestMessage(HttpMethod.Get, "/companies");
        msgGet.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var response = await _client.SendAsync(msgGet);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var list = await response.Content.ReadFromJsonAsync<List<CompanyResponse>>();
        Assert.NotNull(list);
        Assert.Contains(list, c => c.Name == "My Unique Company");
    }

    [Fact]
    public async Task FindBySlug_ExistingSlug_Returns200OK()
    {
        // Arrange
        var token = await RegisterAndGetTokenAsync();
        var customSlug = $"find-slug-{Guid.NewGuid():N}";

        var request = new CreateCompanyRequest { Name = "Find Slug Co", Slug = customSlug };
        var msgCreate = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request)
        };
        msgCreate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        await _client.SendAsync(msgCreate);

        // Act
        var msgGet = new HttpRequestMessage(HttpMethod.Get, $"/companies/slug/{customSlug}");
        msgGet.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var response = await _client.SendAsync(msgGet);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var company = await response.Content.ReadFromJsonAsync<CompanyResponse>();
        Assert.NotNull(company);
        Assert.Equal(customSlug, company.Slug);
    }

    [Fact]
    public async Task UpdateCompany_AsOwner_ReturnsUpdatedCompany()
    {
        // Arrange
        var token = await RegisterAndGetTokenAsync();

        var request = new CreateCompanyRequest { Name = "Original Name" };
        var msgCreate = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request)
        };
        msgCreate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var resCreate = await _client.SendAsync(msgCreate);
        var created = await resCreate.Content.ReadFromJsonAsync<CompanyResponse>();

        var updateRequest = new UpdateCompanyRequest
        {
            Name = "Updated Company Name"
        };
        var msgUpdate = new HttpRequestMessage(HttpMethod.Patch, $"/companies/{created!.Id}")
        {
            Content = JsonContent.Create(updateRequest)
        };
        msgUpdate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

        // Act
        var response = await _client.SendAsync(msgUpdate);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var updated = await response.Content.ReadFromJsonAsync<CompanyResponse>();
        Assert.NotNull(updated);
        Assert.Equal("Updated Company Name", updated.Name);
    }

    [Fact]
    public async Task UpdateCompany_NotOwner_ReturnsUnauthorized()
    {
        // Arrange - Owner creates company
        var ownerToken = await RegisterAndGetTokenAsync("owner");
        var otherToken = await RegisterAndGetTokenAsync("other");

        var request = new CreateCompanyRequest { Name = "Owner Company" };
        var msgCreate = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request)
        };
        msgCreate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", ownerToken);
        var resCreate = await _client.SendAsync(msgCreate);
        var created = await resCreate.Content.ReadFromJsonAsync<CompanyResponse>();

        // Act - Other user tries to update
        var updateRequest = new UpdateCompanyRequest { Name = "Hacked Name" };
        var msgUpdate = new HttpRequestMessage(HttpMethod.Patch, $"/companies/{created!.Id}")
        {
            Content = JsonContent.Create(updateRequest)
        };
        msgUpdate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", otherToken);
        var response = await _client.SendAsync(msgUpdate);

        // Assert
        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
    }

    [Fact]
    public async Task RemoveCompany_AsOwner_Returns200OK()
    {
        // Arrange
        var token = await RegisterAndGetTokenAsync();

        var request = new CreateCompanyRequest { Name = "Company to Delete" };
        var msgCreate = new HttpRequestMessage(HttpMethod.Post, "/companies")
        {
            Content = JsonContent.Create(request)
        };
        msgCreate.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var resCreate = await _client.SendAsync(msgCreate);
        var created = await resCreate.Content.ReadFromJsonAsync<CompanyResponse>();

        // Act
        var msgDelete = new HttpRequestMessage(HttpMethod.Delete, $"/companies/{created!.Id}");
        msgDelete.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var response = await _client.SendAsync(msgDelete);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        // Verify deleted
        var msgFind = new HttpRequestMessage(HttpMethod.Get, $"/companies/{created.Id}");
        msgFind.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
        var resFind = await _client.SendAsync(msgFind);
        Assert.Equal(HttpStatusCode.NotFound, resFind.StatusCode);
    }
}
